name: pull from production-branch

on:
  push:
    branches:
      - production

jobs:
  pull_production_branch:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: pull
        run: |
          git checkout production
          git pull origin production
